#!/usr/bin/env bash

clean() { rm -rf /tmp/avfinstall; }

# Install deps
apk add bind-tools dnsmasq findutils gcc grep iproute2 iptables jq \
    libqrencode musl-dev openconnect openrc openssh-server openssl \
    openvpn py2-setuptools python2 python2-dev sed vim vimdiff \
    wireguard-tools yaml-dev

# Setup install dir
clean
mkdir -p /tmp/avfinstall
cd /tmp/avfinstall

# Install certifyme for OpenVPN
git clone https://gitlab.com/mjwhitta/certifyme.git && \
    (cd certifyme && ./installer)

# Install obfsproxy for OpenVPN
git clone https://github.com/isislovecruft/obfsproxy.git && \
    (cd obfsproxy && python2 ./setup.py install --user)

# Uninstall build deps
apk del -r binutils gcc musl-dev python2-dev yaml-dev

# Tweak some system config files
echo "tun" >/etc/modules-load.d/avf.conf
echo "net.ipv4.ip_forward=1" >/etc/sysctl.d/avf.conf
if [[ ! -e /etc/dnsmasq.d/default.conf ]]; then
    cat >/etc/dnsmasq.d/default.conf <<EOF
no-resolv

domain=$(grep -ioPs "^search\s+\K.+" /etc/resolv.conf)
expand-hosts

$(
    while read -r ns; do
        echo "server=$ns"
    done < <(grep -ioPs "^nameserver\s+\K.+" /etc/resolv.conf)
)
EOF
fi
sed -i -r "/^nameserver/d" /etc/resolv.conf
echo "nameserver 127.0.0.1" >>/etc/resolv.conf

# Clean up
cd
clean

# Reboot
echo "Now is a good time to reboot"
